name: CI Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - dev
      - main

jobs:
  validate-conventional-commit:
    name: Validate Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - name: Validate Conventional Commit
        uses: amannn/action-semantic-pull-request@v5
        with:
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify:
    name: Lint, Build and Code Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Oxlint
        run: npm run lint

      - name: Build Next.js Application
        run: npm run build
